---
version: '3'

volumes:
  data-postgres: {}
  data-opennms: {}
  data-opennms-cfg: {}
  data-es01: {}
  data-grafana: {}

services:
  database:
    image: postgres:15
    environment:
      TZ: Europe/Berlin
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - data-postgres:/var/lib/postgresql/data
    command: ["postgres", "-N", "200"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 3

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      TZ: Europe/Berlin
      discovery.type: single-node
      node.name: es-node-01
      cluster.name: clab-frr-lab01
      search.max_buckets: 250000
    ports:
      - "9200:9200/tcp"
      - "9300:9300/tcp"
    volumes:
      - data-es01:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
    healthcheck:
      test: curl http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    depends_on:
      es01:
        condition: service_healthy
    environment:
      TZ: ${TIMEZONE:-America/New_York}
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - "5601:5601/tcp"
    healthcheck:
      test: curl http://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 50

  horizon:
    image: opennms/horizon:latest
    depends_on:
      database:
        condition: service_healthy
      es01:
        condition: service_healthy
    environment:
      TZ: Europe/Berlin
    volumes:
      - data-opennms:/opennms-data
      - data-opennms-cfg:/opt/opennms/etc
      - ./container-fs/opt/opennms/deploy:/opt/opennms/deploy
      - ./container-fs/opt/opennms-overlay:/opt/opennms-overlay
      - ./container-fs/etc/conf.d/confd.toml:/etc/confd/confd.toml
    command: ["-s"]
    ports:
      - '8101:8101/tcp'
      - '8980:8980/tcp'
      - '61616:61616/tcp'
      - '162:1162/udp'
    healthcheck:
      test: [ "CMD", "curl", "-f", "-I", "http://localhost:8980/opennms/login.jsp" ]
      interval: 1m
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    depends_on:
      horizon:
        condition: service_started
    environment:
      TZ: Europe/Berlin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_INSTALL_PLUGINS: opennms-opennms-app,grafana-piechart-panel,neocat-cal-heatmap-panel,briangann-datatable-panel
    volumes:
      - data-grafana:/var/lib/grafana
      - ./container-fs/gf-provisioning:/etc/grafana/provisioning/
    ports:
      - "3000:3000/tcp"
